version: "3.7"

services:
  local:
    image: mysql_store_management:latest
    build:
      context: .
      cache_from:
        - mysql_store_management
      dockerfile: Dockerfile
    ports:
      - "33069:3306"
