version: "3.7"

services:
  app:
    image: app_store_management:latest
    build:
      context: .
      cache_from:
        - store_management
      dockerfile: kubernetes/app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql_store_management:latest
    build:
      context: .
      cache_from:
        - mysql_store_management
      dockerfile: kubernetes/database/Dockerfile
    ports:
      - "33069:3306"
    volumes:
      - store_management_volume:/var/lib/mysql

volumes:
  store_management_volume:
    name: sm_data

