service: store-management

app: store-management

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2     # optional, default: us-east-1
  memorySize: 128           # optional, in MB, default: 1024
  stage: ${env:SM_STAGE}                # optional, default: dev
  environment: ${file(./env.js)}

functions:
  store_management_api:
    name: store_management
    handler: ./lambdas/handler.index
    events:
      - http:
          path: /{endpoint+}
          method: ANY
          cors: true

#  GraphQL:
#    handler: graphqls/dist/handler.index
#    events:
#      - http:
#          path: /graphql
#          method: get
#          cors: true
#      - http:
#          path: /graphql
#          method: post
#          cors: true
#      - http:
#          path: /graphql
#          method: options
#          cors: true

custom:
  serverless-offline:
    httpPort: 8080
    noPrependStageInUrl: true

plugins:
  - serverless-offline
